openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/api/gpcproject
  description: Generated server url
paths:
  /products:
    get:
      tags:
      - Products
      description: Get all products
      operationId: getAllProducts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  /products/{name}:
    get:
      tags:
      - Products
      description: Get product by name
      operationId: getProductByName
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
  /products/count:
    get:
      tags:
      - Products
      description: Get number of products
      operationId: countAllProducts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          type: string
        partNumberNR:
          type: string
        companyName:
          type: string
        active:
          type: boolean
    ApiError:
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
        description:
          type: string
